-- V1: Criação das tabelas iniciais (usuarios e checkins)

-- Tabela de Usuários
CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    data_criacao TIMESTAMP NOT NULL
);

-- Tabela de Check-ins
CREATE TABLE checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    tarefa_concluida BOOLEAN NOT NULL,
    diario VARCHAR(1000) NOT NULL,
    data_checkin TIMESTAMP NOT NULL,
    CONSTRAINT fk_checkin_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- Índices para otimização de consultas
CREATE INDEX idx_checkin_usuario_id ON checkins(usuario_id);
CREATE INDEX idx_checkin_data ON checkins(data_checkin DESC);

-- Inserir um usuário de exemplo para testes
INSERT INTO usuarios (nome, email, data_criacao) VALUES
('Usuário de Teste', 'teste@checkin.com', CURRENT_TIMESTAMP);
