-- V2: Adicionar coluna de senha e papel aos usuários e criar tabela de hábitos

-- Adiciona a coluna 'senha' à tabela de usuários. Para usuários existentes,
-- define um valor padrão provisório para que a restrição NOT NULL seja atendida.
ALTER TABLE usuarios ADD COLUMN senha VARCHAR(120) NOT NULL DEFAULT 'changeme';

-- Adiciona a coluna 'role' com valor padrão 'USER'.
ALTER TABLE usuarios ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER';

-- Cria a tabela de hábitos de saúde, com referência ao usuário.
CREATE TABLE habitos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(500),
    meta VARCHAR(100),
    data_criacao TIMESTAMP NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_habito_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- Índice para otimização de consultas por usuário
CREATE INDEX idx_habito_usuario_id ON habitos(usuario_id);